apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-deploy
spec:
  selector:
    matchLabels:
      app: schedule
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
        - name: nodejs
          image: '{{ .Values.werf.image.schedule }}'
          workingDir: /app
          env:
            - name: EKP_PLUGIN_ID
              value: '{{ .Chart.Name }}'
            - name: EKP_PLUGIN_NAME
              value: '.'
            - name: MONGO_URI
              value: '{{ .Values.mongodb.uri }}'
            - name: REDIS_HOST
              value: '{{ .Release.Name }}-redis-master'
            - name: NODE_ENV
              value: '{{ .Values.werf.env | default "production" }}'
            - name: PROXY_HOST
              value: '{{ .Values.proxy.host }}'
            - name: PROXY_PORT
              value: '{{ .Values.proxy.port }}'
